// Code generated by model/sort.go; DO NOT EDIT.

package model

var SortMap = map[string]sortFunc{
	"Pid":       SortByPid,
	"Comm":      SortByComm,
	"State":     SortByState,
	"Ppid":      SortByPpid,
	"Thr":       SortByNumThreads,
	"StartTime": SortByStartTime,
	"OnCPU":     SortByProcessor,
	"UserCPU":   SortByUTime,
	"SysCPU":    SortBySTime,
	"Pri":       SortByPriority,
	"Nice":      SortByNice,
	"CPU":       SortByCPUUsage,
	"Minflt":    SortByMinFlt,
	"Majflt":    SortByMajFlt,
	"Vsize":     SortByVSize,
	"RSS":       SortByRSS,
	"Mem":       SortByMemUsage,
	"Rchar":     SortByRChar,
	"Wchar":     SortByWChar,
	"Rchar/s":   SortByRCharPerSec,
	"Wchar/s":   SortByWCharPerSec,
	"Syscr":     SortBySyscR,
	"Syscw":     SortBySyscW,
	"Syscr/s":   SortBySyscRPerSec,
	"Syscw/s":   SortBySyscWPerSec,
	"Read":      SortByReadBytes,
	"Write":     SortByWriteBytes,
	"Wcancel":   SortByCancelledWriteBytes,
	"R/s":       SortByReadBytesPerSec,
	"W/s":       SortByWriteBytesPerSec,
	"CW/s":      SortByCancelledWriteBytesPerSec,
	"Disk":      SortByDiskUage,
}

func SortByPid(i, j Process) bool {
	return i.Pid > j.Pid
}

func SortByComm(i, j Process) bool {
	return i.Comm > j.Comm
}

func SortByState(i, j Process) bool {
	stodesc := map[string]string{
		"R": "Running",
		"S": "Sleeping",
		"D": "Uninterruptible",
		"I": "Idle",
		"Z": "Zombie",
		"T": "Stopped",
		"t": "Tracing stop",
		"X": "Dead",
		"x": "Dead",
		"K": "Wakekill",
		"W": "Waking",
		"P": "Parked",
	}
	return stodesc[i.State] > stodesc[j.State]
}

func SortByPpid(i, j Process) bool {
	return i.Ppid > j.Ppid
}

func SortByNumThreads(i, j Process) bool {
	return i.NumThreads > j.NumThreads
}

func SortByStartTime(i, j Process) bool {
	return i.StartTime > j.StartTime
}

func SortByProcessor(i, j Process) bool {
	return i.Processor > j.Processor
}

func SortByUTime(i, j Process) bool {
	return i.UTime > j.UTime
}

func SortBySTime(i, j Process) bool {
	return i.STime > j.STime
}

func SortByPriority(i, j Process) bool {
	return i.Priority > j.Priority
}

func SortByNice(i, j Process) bool {
	return i.Nice > j.Nice
}

func SortByCPUUsage(i, j Process) bool {
	return i.CPUUsage > j.CPUUsage
}

func SortByMinFlt(i, j Process) bool {
	return i.MinFlt > j.MinFlt
}

func SortByMajFlt(i, j Process) bool {
	return i.MajFlt > j.MajFlt
}

func SortByVSize(i, j Process) bool {
	return i.VSize > j.VSize
}

func SortByRSS(i, j Process) bool {
	return i.RSS > j.RSS
}

func SortByMemUsage(i, j Process) bool {
	return i.MemUsage > j.MemUsage
}

func SortByRChar(i, j Process) bool {
	return i.RChar > j.RChar
}

func SortByWChar(i, j Process) bool {
	return i.WChar > j.WChar
}

func SortByRCharPerSec(i, j Process) bool {
	return i.RCharPerSec > j.RCharPerSec
}

func SortByWCharPerSec(i, j Process) bool {
	return i.WCharPerSec > j.WCharPerSec
}

func SortBySyscR(i, j Process) bool {
	return i.SyscR > j.SyscR
}

func SortBySyscW(i, j Process) bool {
	return i.SyscW > j.SyscW
}

func SortBySyscRPerSec(i, j Process) bool {
	return i.SyscRPerSec > j.SyscRPerSec
}

func SortBySyscWPerSec(i, j Process) bool {
	return i.SyscWPerSec > j.SyscWPerSec
}

func SortByReadBytes(i, j Process) bool {
	return i.ReadBytes > j.ReadBytes
}

func SortByWriteBytes(i, j Process) bool {
	return i.WriteBytes > j.WriteBytes
}

func SortByCancelledWriteBytes(i, j Process) bool {
	return i.CancelledWriteBytes > j.CancelledWriteBytes
}

func SortByReadBytesPerSec(i, j Process) bool {
	return i.ReadBytesPerSec > j.ReadBytesPerSec
}

func SortByWriteBytesPerSec(i, j Process) bool {
	return i.WriteBytesPerSec > j.WriteBytesPerSec
}

func SortByCancelledWriteBytesPerSec(i, j Process) bool {
	return i.CancelledWriteBytesPerSec > j.CancelledWriteBytesPerSec
}

func SortByDiskUage(i, j Process) bool {
	return i.DiskUage > j.DiskUage
}
