// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package store

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cgroupCgroupNetStat struct {
	_        structs.HostLayout
	RxPacket uint64
	RxByte   uint64
	TxPacket uint64
	TxByte   uint64
}

// loadCgroup returns the embedded CollectionSpec for cgroup.
func loadCgroup() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgroupBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cgroup: %w", err)
	}

	return spec, err
}

// loadCgroupObjects loads cgroup and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cgroupObjects
//	*cgroupPrograms
//	*cgroupMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCgroupObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCgroup()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cgroupSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupSpecs struct {
	cgroupProgramSpecs
	cgroupMapSpecs
	cgroupVariableSpecs
}

// cgroupProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupProgramSpecs struct {
	CgroupRmdir         *ebpf.ProgramSpec `ebpf:"cgroup_rmdir"`
	CountEgressPackets  *ebpf.ProgramSpec `ebpf:"count_egress_packets"`
	CountIngressPackets *ebpf.ProgramSpec `ebpf:"count_ingress_packets"`
}

// cgroupMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupMapSpecs struct {
	CgroupNetStats *ebpf.MapSpec `ebpf:"cgroup_net_stats"`
}

// cgroupVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupVariableSpecs struct {
}

// cgroupObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupObjects struct {
	cgroupPrograms
	cgroupMaps
	cgroupVariables
}

func (o *cgroupObjects) Close() error {
	return _CgroupClose(
		&o.cgroupPrograms,
		&o.cgroupMaps,
	)
}

// cgroupMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupMaps struct {
	CgroupNetStats *ebpf.Map `ebpf:"cgroup_net_stats"`
}

func (m *cgroupMaps) Close() error {
	return _CgroupClose(
		m.CgroupNetStats,
	)
}

// cgroupVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupVariables struct {
}

// cgroupPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupPrograms struct {
	CgroupRmdir         *ebpf.Program `ebpf:"cgroup_rmdir"`
	CountEgressPackets  *ebpf.Program `ebpf:"count_egress_packets"`
	CountIngressPackets *ebpf.Program `ebpf:"count_ingress_packets"`
}

func (p *cgroupPrograms) Close() error {
	return _CgroupClose(
		p.CgroupRmdir,
		p.CountEgressPackets,
		p.CountIngressPackets,
	)
}

func _CgroupClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgroup_bpfel.o
var _CgroupBytes []byte
