// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package store

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processEvent struct {
	_                   structs.HostLayout
	Pid                 int32
	Ppid                int32
	ExitCode            int64
	Comm                [16]uint8
	Cmdline             [32]uint8
	Utime               uint64
	Stime               uint64
	StartTime           uint64
	EndTime             uint64
	NumThreads          int32
	_                   [4]byte
	OnCpu               uint64
	Priority            uint64
	Nice                uint64
	DelayacctBlkioTicks uint64
	MinFlt              uint64
	MajFlt              uint64
	VssPages            uint64
	RssPages            uint64
	Rchar               uint64
	Wchar               uint64
	Syscr               uint64
	Syscw               uint64
	IoReadBytes         uint64
	IoWriteBytes        uint64
	CancelledWriteBytes uint64
}

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
	processVariableSpecs
}

// processProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	HandleExit *ebpf.ProgramSpec `ebpf:"handle_exit"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// processVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
	processVariables
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.Events,
	)
}

// processVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	HandleExit *ebpf.Program `ebpf:"handle_exit"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.HandleExit,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpfel.o
var _ProcessBytes []byte
