// Code generated by "stringer -linecomment -output=proc_string.go -type=ProcState,ProcPolicy"; DO NOT EDIT.

package procfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Running-82]
	_ = x[Sleeping-83]
	_ = x[Uninterruptible-68]
	_ = x[Idle-73]
	_ = x[Zombie-90]
	_ = x[Stopped-84]
	_ = x[TracingStopped-116]
	_ = x[Dead-88]
	_ = x[Deadx-120]
	_ = x[Wakekill-75]
	_ = x[Waking-87]
	_ = x[Parked-80]
}

const (
	_ProcState_name_0 = "Uninterruptible"
	_ProcState_name_1 = "Idle"
	_ProcState_name_2 = "Wakekill"
	_ProcState_name_3 = "Parked"
	_ProcState_name_4 = "RunningSleepingStopped"
	_ProcState_name_5 = "WakingDead"
	_ProcState_name_6 = "Zombie"
	_ProcState_name_7 = "TracingStopped"
	_ProcState_name_8 = "Deadx"
)

var (
	_ProcState_index_4 = [...]uint8{0, 7, 15, 22}
	_ProcState_index_5 = [...]uint8{0, 6, 10}
)

func (i ProcState) String() string {
	switch {
	case i == 68:
		return _ProcState_name_0
	case i == 73:
		return _ProcState_name_1
	case i == 75:
		return _ProcState_name_2
	case i == 80:
		return _ProcState_name_3
	case 82 <= i && i <= 84:
		i -= 82
		return _ProcState_name_4[_ProcState_index_4[i]:_ProcState_index_4[i+1]]
	case 87 <= i && i <= 88:
		i -= 87
		return _ProcState_name_5[_ProcState_index_5[i]:_ProcState_index_5[i+1]]
	case i == 90:
		return _ProcState_name_6
	case i == 116:
		return _ProcState_name_7
	case i == 120:
		return _ProcState_name_8
	default:
		return "ProcState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NORMAL-0]
	_ = x[FIFO-1]
	_ = x[RR-2]
	_ = x[BATCH-3]
	_ = x[IDLE-5]
	_ = x[DEADLINE-6]
}

const (
	_ProcPolicy_name_0 = "NORMALFIFORRBATCH"
	_ProcPolicy_name_1 = "IDLEDEADLINE"
)

var (
	_ProcPolicy_index_0 = [...]uint8{0, 6, 10, 12, 17}
	_ProcPolicy_index_1 = [...]uint8{0, 4, 12}
)

func (i ProcPolicy) String() string {
	switch {
	case i <= 3:
		return _ProcPolicy_name_0[_ProcPolicy_index_0[i]:_ProcPolicy_index_0[i+1]]
	case 5 <= i && i <= 6:
		i -= 5
		return _ProcPolicy_name_1[_ProcPolicy_index_1[i]:_ProcPolicy_index_1[i+1]]
	default:
		return "ProcPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
